### ISSUE TITLE
y.ticks is not a function

### ISSUE THREAD

**Issue by shamanking** [JesperLekland/react-native-svg-charts#224] opened 2018-08-27 12:32 UTC
I use YAxis as code:

```
 <View style={{ flexDirection: 'row', height: 200, paddingVertical: 16 }}>
                <YAxis
                    data={data}
                    yAccessor={({ index }) => index}
                    scale={scale.scaleBand}
                    contentInset={{ top: 10, bottom: 10 }}
                    spacing={0.2}
                    formatLabel={(_, index) => data[ index ].label}
                />
                <BarChart
                    style={{ flex: 1, marginLeft: 8 }}
                    data={data}
                    horizontal={true}
                    yAccessor={({ item }) => item.value}
                    svg={{ fill: 'rgba(134, 65, 244, 0.8)' }}
                    contentInset={{ top: 10, bottom: 10 }}
                    spacing={0.2}
                    gridMin={0}
                >
                    <Grid direction={Grid.Direction.VERTICAL}/>
                </BarChart>
            </View>
```

But, it had error: y.ticks is not a function(In 'y.ticks(numberOfTicks)', 'y.ticks' is undefined

**Comment by shamanking** [comment] 2018-08-27 13:32
It's ok with replace scale.scaleBand by scale.ScaleBand
But what is index in formatLabel={(_, index) => data[ index ].label}
My data: 
```
const datachart = [
      {
        value: 10,
        label: 'One',
      },
      {
        value: 10,
        label: 'Two',
      },
      {
        value: 10,
        label: 'Three',
      },
     {
        value: 10,
        label: 'Four',
      },
```
    ]
And index is 0, 1, 2, 3, 4, ..., 15 ?

When I remove one element, index is 0, 1, 2, 3, 4 ?
What is logic for it ?

**Comment by gxfan** [comment] 2019-01-21 13:47
I have the same problem, i use version 5.1.1 to solve it finally.

**Comment by ankushdec1993** [comment] 2019-05-30 19:14
is there a solution this only happens in android

**Comment by oscar-gallog** [comment] 2019-08-23 06:59
Same problem here, this is not working at all. It happens on iOS too.

**Comment by smubarak-ali** [comment] 2019-09-27 06:29
I am facing the same exact problem :(

**Comment by jbernhardt23** [comment] 2019-10-28 19:02
I'm having the same issues and it seems that the problem comes in the way that the `YAxis` is comparing the `scale.scaleBand` function. In the source file of `YAxis` there is a comparison of `scale.scaleBand` which return either `values` or the `y.ticks()` function. 

`const ticks = scale === d3Scale.scaleBand ? values : y.ticks(numberOfTicks);`

This comparison is failing to return true and is returning the `y.ticks()` that is not defined (should return `values` since we are passing `scaleBand` as the `scale` prop. 

Since this operation is just comparing the the two functions to validate that the `scale.scaleBand` is being used, I managed to fix this by returning the string value of the functions rather than comparing the plain function.

`const ticks = scale.toString() === d3Scale.scaleBand.toString() ? values : y.ticks(numberOfTicks);`

**Comment by jbernhardt23** [comment] 2019-10-29 13:46
I'm having the same issue and it seems that the problem is the in way that `YAxis` is doing comparisons between the `scale` prop being passed to the component and the `scale.scaleBrand` used from the `d3-scale` dependency used in the library. 

This particular ternary operation `const ticks = scale === d3Scale.scaleBand ? values : y.ticks(numberOfTicks);` is returning false even though you passed the correct scale and as a result, the undefined function `y.ticks(numberOfTicks)` is being returned instead of `values`. 

I've managed to solve this by using the same `d3-scale` dependency as the library and changing all `scale === d3Scale.scaleBand` occurrences to `scale.toString() === d3Scale.scaleBand.toString()`.

I have a PR open https://github.com/JesperLekland/react-native-svg-charts/pull/394

**Comment by usrbowe** [comment] 2019-11-12 06:41
I feel this might be related: https://github.com/JesperLekland/react-native-svg-charts/issues/392#issuecomment-550995454

@jbernhardt23 I'll try to raise PR to fix that. So we can use the `scaleBand`

**Comment by usrbowe** [comment] 2019-11-16 05:23
closing this duplicate issue, and keeping this for reference: #392

**Closed by usrbowe** 2019-11-16 05:23 UTC
