### ISSUE TITLE
Labels not re-rendering correctly when data changes.

### ISSUE THREAD

**Issue by AndrePech** [JesperLekland/react-native-svg-charts#135] opened 2018-05-07 15:10 UTC
### What is the problem?

Labels and XAxis not re-rendering properly when the data changes.
The old values are still visible, overlapping the new ones.

Before data changes: (ok)

![simulator screen shot - iphone 6 - 2018-05-07 at 11 57 03](https://user-images.githubusercontent.com/4999683/39708820-8d5b0c2c-51ee-11e8-82aa-0e6eaec80ac3.png)

After:

![simulator screen shot - iphone 6 - 2018-05-07 at 11 57 44](https://user-images.githubusercontent.com/4999683/39708823-8ec7a386-51ee-11e8-9f75-ae64ddfcfa0b.png)

### When does it happen?

When the data changes and the chart re-renders.

### Code to reproduce

```javascript
renderPeriodoBar() {

        if (this.props.dashboard.caseVolume) {

            console.log('DASH',this.props.dashboard.caseVolume);

            const values = [10,20,30,40];
            const labels = ["A","B","C","D"];

            const axesSvg = { fontSize: 10, fill: this.colors.secondary_text, textAlign: 'center' };
            const verticalContentInset = { top: 10, bottom: 10 }
            const xAxisHeight = 25;

            var max = Math.max(...values);

            const Labels = ({ x, y, bandwidth, data }) => (
                data.map((value, index) => (
                    <T
                        belowChart={true}
                        key={index}
                        y={y(value) - 10}
                        x={x(index) + (bandwidth / 2)}
                        fontSize={10}
                        font={{
                            fontFamily: 'Roboto-Light',
                        }}
                        fontData={{ name: 'Roboto-Light' }}
                        fill={this.colors.secondary_text}
                        alignmentBaseline={'middle'}
                        textAnchor={'middle'}>
                        {value}
                    </T>
                ))
            )

            return (
                <View style={{ height: 180, paddingTop: 12, flexDirection: 'row' }}>
                    <View style={{ flex: 1, marginLeft: 0 }}>
                        <BarChart
                            data={values}
                            style={{ flex: 1 }}
                            gridMin={0}
                            gridMax={max * 1.5}
                            contentInset={{ verticalContentInset }}
                            svg={{
                                fill: this.colors.accent,
                                opacity: 0.80,
                            }}>
                            <Labels belowChart={true} />
                        </BarChart>
                        <XAxis
                            style={{ marginTop: 6, height: xAxisHeight }}
                            data={values}
                            scale={scale.scaleBand}
                            formatLabel={(value, index) => labels[index]}
                            svg={axesSvg}
                        />
                    </View>
                </View>)
        }
}

render(){
    return(
         <View>
         {this.renderPeriodoBar()}
        </View>
     )
}
```

Just call the above function on the render method, then change the data inside the function and re-render 

### What platform?

* [X ] iOS 11

React Native version: 0.54.3

**Comment by JesperLekland** [comment] 2018-05-08 07:30
Hi @AndrePech. Interesting, this should of course not be the case. Which version of react-native-svg are you using? We've gotten reports of problems with versions > 6.2.2

**Comment by AndrePech** [comment] 2018-05-08 13:06
I am using react-native-svg version 6.2.1.

By now I am not rendering the charts while the data is being updated, it prevents this issue from happening.

**Comment by JesperLekland** [comment] 2018-05-08 14:33
hmm strange. I'm going to need you to update your `code to reproduce`, I can't possibly know what all the variables are supposed to be. Please provide an example I can run without modification. As a maintainer I can't possibly troubleshoot all problems without runnable code provided

**Comment by AndrePech** [comment] 2018-05-08 15:25
it is updated o/

Let me know if you need something more!
Thank you very much for maintaining this incredible repo!!

**Comment by JesperLekland** [comment] 2018-05-09 08:54
Thank you, still missing a bunch though. What is the `T` component for example? And `this.props.dashboard.caseVolume`? Please provide the entire file (including imports) to help me out as much as possible. The absolute best way to do things like this is to provide a [snack](https://snack.expo.io/).

**Comment by JesperLekland** [comment] 2018-06-03 11:09
Closing due to lack of reproducible example

**Closed by JesperLekland** 2018-06-03 11:09 UTC

**Comment by animaonline** [comment] 2018-09-02 10:16
This should be reopened as this still happens, and can easily be reproduced
