### ISSUE TITLE
Incorrect layered-charts , when the values in second chart is zero.  

### ISSUE THREAD

**Issue by sanjayknair5** [JesperLekland/react-native-svg-charts#136] opened 2018-05-09 17:50 UTC
### What is the problem?
The scale for chart one and chart 2 differs when the maximum value in both the  data sets are different or When second area chart has maximum value like 1, 5 etc. 
-->

### What platform?

* [ ] Android 

React Native version: 0.55.2

### Code to reproduce

```javascript
 render() {

   

        const data0  = [ 50, 10, 40, 95, 0, 0, 85, 91, 35, 53, 0, 24, 50, 0, 0 ]
        const data1 =  [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ]
        return (
            <View style={ { flexDirection: 'row', height: 200 } }>
                <AreaChart
                    style={ { flex: 1 } }
                    data={ data0 }
                    svg={{ fill: 'rgba(134, 65, 244, 0.5)' }}
                    contentInset={ { top: 20, bottom: 0 } } 
                    curve={ shape.curveNatural }
                    ticks={1}
                >
                    
                </AreaChart>
                <AreaChart
                    style={ StyleSheet.absoluteFill }
                    data={ data1 }
                    svg={{ fill: 'rgba(34, 128, 176, 0.5)' }}
                    contentInset={ { top: 20, bottom: 0 } }
                    curve={ shape.curveNatural }
                    ticks={1}
                />

            </View>
        )
    }
```

![Uploading WhatsApp Image 2018-05-09 at 11.12.43 PM.jpeg…]()

**Comment by JesperLekland** [comment] 2018-05-13 09:29
Your image seems to have failed uploading but I think I understand the issue. You will have to use the `gridMin` and `gridMax` props to align the extents of the charts (i.e this is expected behaviour since the charts don't know of each other).  Closing this as it's not really an issue with the library.

**Closed by JesperLekland** 2018-05-13 09:29 UTC

**Comment by sarykemmoun** [comment] 2018-08-01 09:05
Hello. I have this issue too. I didn't understand your solution since I didn't see in the docs  `gridMin`  and `gridMax`. Could you tell me what is the meaning of this props? (Setting gridMin= {Math.min(data)}
gridMax= {Math.max(data)} didn't help.)

My Code is:
`const data = [8, 0, 5, 0, 0, 0, 4];
`
```
                    <AreaChart
                        style={{ height: deviceHeight * 0.17, width: '99%' }}
                        curve={ shape.curveNatural }
                        data={data}
                         contentInset={{ top: 40, bottom: 10 }}
                        svg={{ fill: 'url(#gradient)' }}
                    >
```

![screenshot from 2018-08-01 12-03-18](https://user-images.githubusercontent.com/28590349/43512207-1cc4119c-9583-11e8-97f6-5999b74ed359.png)

**Comment by JesperLekland** [comment] 2018-08-01 09:10
gridMin/Max is deprecated in favour of `yMin/yMax`, use those instead to align the charts

**Comment by sarykemmoun** [comment] 2018-08-01 10:33
Thanks, @JesperLekland for the response.
yMin didn't solve it for me.
I think that its because of this line `contentInset={{ top: 40, bottom: 20 }}`
I must set the bottom to avoid the decorator to be cut off.
Do you have any solution for it?

**Comment by sarykemmoun** [comment] 2018-08-01 11:06
Finally, I fixed it by removing `contentInset={{ top: 40, bottom: 20 }}`, adding `yMin={0}`
And using custom the `cy` property of the decorator (`react-native-svg.Circle`) in case of value 0 to avoid the decorator to be cut.
