### ISSUE TITLE
React Native Web compatibility

### ISSUE THREAD

**Issue by Elijen** [JesperLekland/react-native-svg-charts#50] opened 2018-02-14 16:11 UTC
Is `react-native-web` compatibility planned? It seems that it should be possible to make this library compatible with both `react-native` and `react-native-web` but some work is necessary.

I was able to make it almost work by using webpack aliases:

`react-native` -> `react-native-web`
`react-native-svg` -> `svgs`

The biggest problem seems to be native only code such as `setNativeProps` and platform specific files (horizontal-labeled-bar-chart-component.android.js` and `horizontal-labeled-bar-chart-component.ios.js`).

I was able to hack the code quickly to make it render in a browser, so I think it should not take much effort to solve this properly (although I am not very familiar with the project so can't tell for sure)

<img width="667" alt="screen shot 2018-02-14 at 17 09 42" src="https://user-images.githubusercontent.com/1304054/36214540-0018ca9a-11aa-11e8-9bbe-c7314762f47d.png">

**Comment by JesperLekland** [comment] 2018-02-14 18:02
Interesting. It's not something that is planned, nor has it been considered before. The platform specific files should actually be removed (will do that in next release), they're not exposed through the lib and are just some experiments I did in the early stages. The setNativeProps is something that is needed for the animations though, not sure how to work around that. Maybe with a `.native` file extension for that specific implementation. 

This is however not something I'll prioritise but your are free to submit a PR :)

**Comment by wrsulliv** [comment] 2018-02-16 05:14
@Elijen Thanks for the tip on `svgs`.  I too am using `react-native-svg-charts` with `react-native-web`.  I encountered the same `horizontal-labeled-bar-chart-component` issue, but removed these files from my fork for the time being.  Additionally, I was using `create-react-app`, but I ejected to manually alter the webpack config.

It looks like `setNativeProps` is currently used in only one place:  `src/animated-path.js`.  If this is the only native specific code (excluding the mentioned component) then it seems supporting `react-native-web` out of the box may require minimal changes?  Possibly with some code to degrade to a non-native setting when the option isn't available?  I'm not sure either..

Anyways, I'm posting here to both express interest in this feature and confirm that I was able to reproduce with the steps listed in the issue. 

@JesperLekland Thanks for the great lib, I'm getting good looking charts across both native and web!

**Comment by JesperLekland** [comment] 2018-02-20 16:25
I've removed the the `horizontal-labeled-bar-chart` in version 3.0.0. I haven't gotten around to modifying `setNativeProps` yet though, just wanted to let you guys know.

**Comment by Elijen** [comment] 2018-02-20 17:33
@JesperLekland Thanks for the heads up. I think the problem might be in `svgs` as they use stateless components that don't support refs. Hence `this.component` is undefined, they also should add setNativeProps support if not added already.

I've just made it work without animation by adding a check before the setNativeProps call on my fork.

**Comment by JesperLekland** [comment] 2018-02-27 21:34
One thing I just thought of, `animated` is default `false` in 3.0.0. Is it still an issue?

**Comment by AlexBrasileiro** [comment] 2018-04-10 19:19
Hello person, I'm having the same difficulty as @Elijen to work with react-native-web.

I'm tried to do this in my webpack config: `'react-native-svg': 'svgs'`, but I did not succeed.

**I continue with the error: You may need an appropriate loader to handle this file type.**

Any idea?

Thank you so much :)

**Comment by zomars** [comment] 2018-04-24 17:16
Care to share your fork @Elijen ?

**Comment by DaKaZ** [comment] 2018-04-26 22:57
@AlexBrasileiro we've had good luck using react-native-web.  Basically what is going on is you need to pass many of the react-native modules (like react-native-svg) through babel.  Here is snipit from our webpack config so you can see what we do (I am only posting the relavent section):

```
function modulesToCompile() {
  const modules = [
      "append-transform",
      "react-native-animatable",
      "react-native-bounceable",
      "react-native-datepicker",
      "react-native-elements",
      "react-native-web-linear-gradient",
      "react-native-orientation",
      "react-native-side-menu",
      "react-native-switch-selector",
      "react-native-svg",
      "react-native-svg-charts",
      "react-native-tab-navigator",
      "react-native-tab-view",
      "react-native-table-component",
      "react-native-vector-icons",
      "react-navigation",
      "svgs"
  ];
  return modules.map((m) => path.resolve(__dirname, `../../client/node_modules/${m}`));
}
```
then later on, in the config:
```
const config = {
module: {
    rules: [
      {
        test: /\.jsx?$/,
        include: modulesToCompile(),
        loader: "babel-loader?+cacheDirectory",
        query: {
          presets: ["es2015", "stage-2", "react", "react-native", "flow"],
          plugins: [
            "transform-flow-comments",
            "transform-react-remove-prop-types",
            "transform-dev"
          ]
        }
      },
      {
        test: /\.(gif|jpe?g|png|svg)$/,
        include: [
          path.resolve(
            __dirname,
            "../../client/node_modules/react-native-vector-icons"
          ),
          path.resolve(
            __dirname,
            "../../client/node_modules/react-native-elements"
          ),
          path.resolve(__dirname, "../../client/node_modules/react-navigation"),
          path.resolve(__dirname, "../../client/src/assets/")
        ],
        loader: "file-loader",
        query: { name: "[name].[hash:16].[ext]" }
      },
      {
        test: /\.ttf$/,
        loader: "url-loader", // or directly file-loader
        include: [
          path.resolve(
            __dirname,
            "../../client/node_modules/react-native-vector-icons"
          ),
          path.resolve(__dirname, "../../client/src/assets/fonts")
        ]
      }
    ]
  }
}
```

**Comment by AlexBrasileiro** [comment] 2018-04-28 19:25
@DaKaZ awesome and thank you a lot for the help o/
I will try to apply in our project and will notify you if everything went well. "D

**Comment by dngconsulting** [comment] 2018-04-29 15:11
Given all the tips out there I have also succeed in getting chart work on react-native-web and android/ios. The issue now is that I face a lot of errors/warning like : 

`Warning: React does not recognize the `animationDuration` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `animationduration` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in path (created by Path)
    in Path (at pie-chart.js:142)`

`Warning: React does not recognize the `pressColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `presscolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by View)`

`Warning: Received `true` for a non-boolean attribute `borderless`.

If you want to write it to the DOM, pass a string instead: borderless="true" or borderless={value.toString()}.
    in div (created by View)
    in View (created by Touc`

and so on ....

Do you have any clue ?

**Comment by Elijen** [comment] 2018-05-03 23:00
@zomars Sorry for the late answer. The repo is here: https://github.com/Elijen/react-native-svg-charts/commits/master

I have made some customization to the ProgressCircle as I needed more flexibility and also didn't like the double round edges:
<img width="250" alt="radius" src="https://user-images.githubusercontent.com/1304054/39606597-76b97e64-4f36-11e8-836e-f593e8f9b34c.png">

But didn't think the modifications were clean enough for a PR.

**Comment by JesperLekland** [comment] 2018-05-04 08:32
@Elijen The double round edges are actually fixed in version 5 :)

**Comment by Elijen** [comment] 2018-05-04 10:41
@JesperLekland What about other customization like:
- circleWidth
- borderRadius
- color of the background circle?

With my fork I can produce this:
<img width="136" alt="screen shot 2018-05-04 at 12 41 26" src="https://user-images.githubusercontent.com/1304054/39624152-80b932b2-4f98-11e8-9140-c4ab00b856d5.png">

Maybe I could create a PR after all.

**Comment by JesperLekland** [comment] 2018-05-07 07:25
That sounds like a great PR @Elijen 👍

**Comment by JesperLekland** [comment] 2018-06-03 11:29
All of the above things (regarding the progressCircle) will be in the upcoming release later today

**Comment by JesperLekland** [comment] 2018-06-03 11:30
All of the above things (regarding the progressCircle) will be in the upcoming release later today. Feel free to open a new issue if you find anything else that doesn't work as expected

**Closed by JesperLekland** 2018-06-03 11:30 UTC

**Comment by dario30186** [comment] 2020-11-06 15:55
> Given all the tips out there I have also succeed in getting chart work on react-native-web and android/ios. The issue now is that I face a lot of errors/warning like :
> 
> `Warning: React does not recognize the `animationDuration`prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase`animationduration` instead. If you accidentally passed it from a parent component, remove it from the DOM element. in path (created by Path) in Path (at pie-chart.js:142)`
> 
> `Warning: React does not recognize the `pressColor`prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase`presscolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element. in div (created by View)`
> 
> `Warning: Received `true`for a non-boolean attribute`borderless`.
> 
> If you want to write it to the DOM, pass a string instead: borderless="true" or borderless={value.toString()}.
> in div (created by View)
> in View (created by Touc`
> 
> and so on ....
> 
> Do you have any clue ?
> 
> Sami

Hi,
did you find a solution for the warnings ?

**Comment by dngconsulting** [comment] 2020-11-07 17:17
no
