### ISSUE TITLE
Two colors same graph

### ISSUE THREAD

**Issue by sofiane-soufi** [JesperLekland/react-native-svg-charts#69] opened 2018-03-01 13:57 UTC
Hello,

I'm having some trouble putting two colors on the same chart like this image:

![screen shot 2018-03-01 at 8 56 09 am](https://user-images.githubusercontent.com/14898088/36848147-6fc9d9f8-1d2e-11e8-908b-30ac044cc316.png)
Does anyone have an idea of how can I do so?

Thank you,
Sofiane.

**Comment by JesperLekland** [comment] 2018-03-01 14:14
Hi @sofiane-soufi! 

This is fully supported 🙂 Please take a look at the [examples repo](https://github.com/JesperLekland/react-native-svg-charts-examples), or more specifically [this example](https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/partial-chart/area-chart.js) for inspiration

**Comment by sofiane-soufi** [comment] 2018-03-02 04:06
Hello @JesperLekland 
Thank you for your quick reply.

I'm trying to run the example but it doesn't show anything. When I set the fill to a hex value, I can see the graphic, but using the url(#identifier), doesn't seem to work.

Do you have any idea why?

Thank you,
Sofiane.

**Comment by sofiane-soufi** [comment] 2018-03-02 05:17
Maybe I need react-d3-shape ?

**Comment by JesperLekland** [comment] 2018-03-02 10:10
It's very hard to help without a reproducible demo. 
I can't speak for Expo unfortunately, the library works as intended locally.

**Comment by sofiane-soufi** [comment] 2018-03-02 13:34
Any tips on how I can debug this?

**Comment by sofiane-soufi** [comment] 2018-03-02 13:48
Here's what it says now:

TypeError: Cannot read property 'length' of undefined


Here's the code where the error occur:

```
<AreaChart
            style={ { position: "absolute", height: 50, backgroundColor: "white", width: "85%"} }
            data={[ 0, 8, 10, 15, 3, 7, 13, 7, 24, 28, 12, 7, 23, 30, 15, 26, 10, 9, 6, 19, 8, 20, 21, 4, 23, 0 ]}
            showGrid={false}
            contentInset={ { top: 10, bottom:0} }
            svg={{
            fill: 'url(#gradient)',
                clipPath: 'url(#clip-path-1)',
        }}
            extras={[
                Gradient,
                Clips,
                Line,
                DashedLine,
        ]}
            />
```

**Comment by sofiane-soufi** [comment] 2018-03-02 13:51
On the version that I have, data is dataPoints (according to the AreaChart module). Do you know if I should update it?

**Comment by JesperLekland** [comment] 2018-03-02 16:42
dataPoints is indeed an old version of the library. Use >=3.0.0

**Comment by JesperLekland** [comment] 2018-03-11 16:53
closing this as it's probably due to using old version of library. Feel free to reopen if problem persists

**Closed by JesperLekland** 2018-03-11 16:53 UTC
