### ISSUE TITLE
animate property not working

### ISSUE THREAD

**Issue by Pardeep03315** [JesperLekland/react-native-svg-charts#188] opened 2018-07-09 12:45 UTC
### What platform?

* [ ] iOS 
* [x] Android 

React Native version: 0.xx

### Code to reproduce

```javascript
// put code here
```

**Comment by JesperLekland** [comment] 2018-07-09 15:05
Closing due to incomplete issue. Provide an explanation and reproducible code and/or screenshots, otherwise you're just wasting everybody's time

**Closed by JesperLekland** 2018-07-09 15:05 UTC
