### ISSUE TITLE
Problems with Y-axis bar Chart

### ISSUE THREAD

**Issue by Nexengineer** [JesperLekland/react-native-svg-charts#118] opened 2018-04-20 16:34 UTC
### What platform?

* [x] iOS 
* [ ] Android 

React Native version:  0.55.2

### Code to reproduce

```javascript
<YAxis
                    data={data}
                    yAccessor={({ index }) => index}
                    scale={scale.scaleBand}
                    contentInset={{ top: 10, bottom: 10 }}
                    spacing={0.2}
                    formatLabel={(_, index) => data[ index ].label}
                />```

<!--
### Stacktrace (if crash)
```
It says label is not defined.
<img width="348" alt="screen shot 2018-04-20 at 9 59 06 pm" src="https://user-images.githubusercontent.com/16309506/39062896-c009bb88-44e6-11e8-87a1-a5327aefcb8c.png">
<img width="296" alt="screen shot 2018-04-20 at 9 59 36 pm" src="https://user-images.githubusercontent.com/16309506/39062897-c05f12fe-44e6-11e8-8641-089bd062c65b.png">

```
-->

**Comment by JesperLekland** [comment] 2018-05-17 12:07
Closing this due to lacking "code to reproduce" (what is `data`?)

**Closed by JesperLekland** 2018-05-17 12:07 UTC

**Comment by Nexengineer** [comment] 2018-05-17 12:15
Yeah, this is working good on iPAD not iPhone but i am good for now thanks
