### ISSUE TITLE
Onpressin function doesn't work on android with react-native-svg@8.0.X

### ISSUE THREAD

**Issue by conradjonp** [JesperLekland/react-native-svg-charts#283] opened 2018-12-11 11:37 UTC
### What is the problem?
Onpressin function doesn't work anymore in conjunction of "react-native-svg" on Android with version 8.0.x

### When does it happen?
Have an onpressin function on a Pie Chart on the svg label

### What platform?
* [ ] iOS 
* [x] Android 

React Native version: 0.57

### Code to reproduce

```javascript
var pieData = [20, 30, 10].map((value, index) => ({
    svg: {
        fill: "blue",
        stroke: "blue",
        scale: 1,
        onPressIn: () => {console.log("i was pressed", value, index)},
    },
    key: `pie-${index}`,
}));

<PieChart
    style={{height: 350}}
    data={pieData}
    innerRadius={"60%"}
    outerRadius={"75%"}
    labelRadius={"75%"}/>
```

**Comment by JesperLekland** [comment] 2018-12-15 15:51
Can you confirm this behaviour with an older version of react-native-svg? This library only officially support `^6.2.1`. Have a hard time seeing that this is caused by our library and as such will close this issue

**Closed by JesperLekland** 2018-12-15 15:51 UTC
