### ISSUE TITLE
Tooltip text duplicate showing in top left corner

### ISSUE THREAD

**Issue by ssuchanowski** [JesperLekland/react-native-svg-charts#387] opened 2019-10-03 14:20 UTC
### What is the problem?

Text from tooltip is duplicated and added to top left corner.
![Screenshot 2019-10-03 at 16 18 22](https://user-images.githubusercontent.com/1038270/66134979-7b507a80-e5f9-11e9-939d-d790a5a8fe45.png)

### When does it happen?

Always.

### What platform?

* [x] iOS
* [ ] Android // didn't test

React Native version: 0.59.8
react-native-svg-charts-version: 5.3.0

### Code to reproduce

Just use example with tooltip.

**Comment by Shhzdmrz** [comment] 2019-10-17 08:39
could you please share the sample code to reproduce it?

**Comment by ssuchanowski** [comment] 2019-10-17 08:49
> Just use example with tooltip.

**Comment by usrbowe** [comment] 2019-11-06 07:48
@ssuchanowski which version of `react-native-svg` you use? I remember this was an issue, because this library uses `transparent` color for the text placeholder.

If you can check, I did demo in Expo Snack and I can't reproduce:  https://snack.expo.io/@usrbowe2/543c93

**Comment by ssuchanowski** [comment] 2019-11-06 08:15
It was the default version at that time. Since then I made major changes upgrading RN to most recent and doing tooltips and chart_drag_to_preview logic on my own.

I didn't use expo if that can make any difference.

**Comment by usrbowe** [comment] 2019-11-06 08:54
@ssuchanowski Expo doesn't make much difference in the behaviour of this library. So if there is no way to reproduce, I would close this issue.

**Comment by usrbowe** [comment] 2019-11-16 05:30
@ssuchanowski closing, since there is no reproducible code. Feel free to reopen with reproducible code.

**Closed by usrbowe** 2019-11-16 05:30 UTC

**Comment by ssuchanowski** [comment] 2019-11-16 10:36
Did you even try without expo?

@jk-gan had the same issue, so it is reproducible.

**Comment by usrbowe** [comment] 2019-11-16 12:01
@ssuchanowski I did not, but I'm fairly familiar with this exact issue. So I didn't find reason to verify without expo, especially when there is almost zero difference between those two environments.

But I did test right now and I can't reproduce same issue.

Please, if you still facing this issue, share reproducible code. This would help me debug the issue you and @jk-gan facing.

Tested on:
```
"react-native": "0.61.4",
"react-native-svg": "^9.13.3",
"react-native-svg-charts": "^5.3.0"
```

Exact same code as in Expo Snack I shared above.

**Comment by DanMccloy** [comment] 2020-02-06 10:57
I believe this is a case where the react-native Text element is being imported, instead of the Text Element from react-native-svg. 

Splitting the tooltip out into a different file and ensuring Text is being imported from react-native-svg fixed this issue for me.
